name: 'PR-comment'
description: 'adds PR changes as comment'
author: 'FreemanBoss'

# Define your inputs here.
inputs:
  owner:
    description: 'The owner of the repository (user or organization)'
    required: true
  repo:
    description: 'the repository name'
    required: true
  pr_number:
    description: 'the pull request number'
    required: true
  token:
    description: 'the github API token'
    required: true
outputs:
  time:
    description: 'Your output description here'

runs:
  using: node20
  main: dist/index.js
